### ISSUE TITLE
Authorship for BEP1

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/enhancements#9]
@MicDr Please add your name to the authors list; please add your name to the licensing text at the bottom

@romainsacchi Please add your name to the licensing text at the bottom

**Comment by romainsacchi** [comment]
Done.

**Comment by MicDr** [comment]
Done, though now I am editor and author... umm

**Comment by cmutel** [comment]
I guess this will be relatively common, as the editor's job is to:

> Check that the BEP is ready. The format should be followed, the language 
> should be clear, the ideas should be completely developed. If the BEP is not 
> ready, provide specific feedback to the authors in an issue, and request a pull request.

I don't think we need to worry about this unless it becomes a problem in the future.
